"""add all_styles_mapping

Revision ID: 28e8c0c900c5
Revises: 437446366322
Create Date: 2026-02-08 22:09:43.214581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28e8c0c900c5'
down_revision: Union[str, Sequence[str], None] = '437446366322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('styles', sa.Column('styled_transcript', sa.JSON(), nullable=True))
    op.drop_column('styles', 'spotlight')
    op.drop_column('styles', 'matt')
    op.drop_column('styles', 'dynamic')
    op.drop_column('styles', 'one_line')
    op.drop_column('styles', 'two_lines')
    op.drop_column('styles', 'split_screen')
    op.drop_column('styles', 'minimal')
    op.drop_column('styles', 'three_lines')
    op.add_column('videos', sa.Column('all_styles_mapping', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'all_styles_mapping')
    op.add_column('styles', sa.Column('three_lines', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('styles', sa.Column('minimal', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('styles', sa.Column('split_screen', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('styles', sa.Column('two_lines', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('styles', sa.Column('one_line', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('styles', sa.Column('dynamic', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('styles', sa.Column('matt', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('styles', sa.Column('spotlight', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('styles', 'styled_transcript')
    # ### end Alembic commands ###
