"""add google id to referrer

Revision ID: 339913408d4a
Revises: a975453c3d98
Create Date: 2026-03-01 21:41:07.848510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '339913408d4a'
down_revision: Union[str, Sequence[str], None] = 'a975453c3d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrers', sa.Column('google_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_referrers_google_id'), 'referrers', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referrers_google_id'), table_name='referrers')
    op.drop_column('referrers', 'google_id')
    # ### end Alembic commands ###
