"""add caption_padding to video

Revision ID: 3b7ef482661d
Revises: d2defdef3809
Create Date: 2026-02-11 14:23:27.435704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b7ef482661d'
down_revision: Union[str, Sequence[str], None] = 'd2defdef3809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('caption_padding', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'caption_padding')
    # ### end Alembic commands ###
