"""add video width height fps duration

Revision ID: 437446366322
Revises: 7e41ef9afd84
Create Date: 2026-02-06 17:19:14.389874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '437446366322'
down_revision: Union[str, Sequence[str], None] = '7e41ef9afd84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('width', sa.Float(), nullable=True))
    op.add_column('videos', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('videos', sa.Column('fps', sa.Float(), nullable=True))
    op.alter_column('videos', 'duration',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'duration',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('videos', 'fps')
    op.drop_column('videos', 'height')
    op.drop_column('videos', 'width')
    # ### end Alembic commands ###
