"""add referral tables

Revision ID: 4780f72df307
Revises: 09386afbae36
Create Date: 2026-03-01 17:18:03.793989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4780f72df307'
down_revision: Union[str, Sequence[str], None] = '09386afbae36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referred_by_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referred_by_code')
    # ### end Alembic commands ###
