"""remove user id from referrer

Revision ID: 5f9c686882ad
Revises: 339913408d4a
Create Date: 2026-03-02 11:05:31.855075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f9c686882ad'
down_revision: Union[str, Sequence[str], None] = '339913408d4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('referrers', 'google_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('referrers_user_id_key', 'referrers', type_='unique')
    op.drop_constraint('referrers_user_id_fkey', 'referrers', type_='foreignkey')
    op.drop_column('referrers', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrers', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('referrers_user_id_fkey', 'referrers', 'users', ['user_id'], ['id'])
    op.create_unique_constraint('referrers_user_id_key', 'referrers', ['user_id'])
    op.alter_column('referrers', 'google_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
