"""add video processing fields

Revision ID: 918e17939c13
Revises: 8fa758245704
Create Date: 2026-02-05 18:30:02.043336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '918e17939c13'
down_revision: Union[str, Sequence[str], None] = '8fa758245704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'transcript',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'transcript',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
