"""change referrals table to add referrers details, and payouts and so on

Revision ID: a975453c3d98
Revises: 4780f72df307
Create Date: 2026-03-01 18:31:14.462315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a975453c3d98'
down_revision: Union[str, Sequence[str], None] = '4780f72df307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrers', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('referrers', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('referrers', sa.Column('address', sa.String(), nullable=True))
    op.add_column('referrers', sa.Column('paypal_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referrers', 'paypal_email')
    op.drop_column('referrers', 'address')
    op.drop_column('referrers', 'last_name')
    op.drop_column('referrers', 'first_name')
    # ### end Alembic commands ###
