"""add render job id

Revision ID: cc27bf38c963
Revises: 6bad338f7e1f
Create Date: 2026-02-10 21:53:53.826430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc27bf38c963'
down_revision: Union[str, Sequence[str], None] = '6bad338f7e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('render_job_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'render_job_id')
    # ### end Alembic commands ###
