"""add fire and return method to generate captions or /generate endpoint

Revision ID: d2defdef3809
Revises: cc27bf38c963
Create Date: 2026-02-11 12:32:45.099732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2defdef3809'
down_revision: Union[str, Sequence[str], None] = 'cc27bf38c963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('progress', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('current_step', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'current_step')
    op.drop_column('videos', 'progress')
    # ### end Alembic commands ###
